Add "require 'ostruct'" in "event_store_test"
I get the following error without this:

    $ bundle exec rake

    ...

    Clockwork::DatabaseEvents::EventStore::#register#test_0001_adds the event to the event group:
    NameError: uninitialized constant OpenStruct
        /Users/jordan/repos/clockwork/test/database_events/event_store_test.rb:15:in `block (3 levels) in <top (required)>'

I'm not sure why CircleCI doesn't seem to be exhibiting the same error.